# Generated by Django 2.0.6 on 2018-07-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('address', models.TextField(default='')),
                ('email', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
